// frontend-react/src/pages/Register.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import "./Register.css";

const Register = () => {
  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState(""); // Inicializa correctamente

  const navigate = useNavigate();

  const handleRegister = async (event) => {
    event.preventDefault();
    setLoading(true);
    setErrorMessage("");

    const data = { name, username, email, password };

    try {
      const response = await fetch("http://127.0.0.1:8000/users/register", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorDetail = await response.json();
        console.error("Error en el registro:", errorDetail);
        throw new Error(errorDetail.detail || "Error al registrarse");
      }

      alert("Usuario registrado correctamente");
      navigate("/login"); // Redirige al formulario de login
    } catch (error) {
      console.error("Error en la solicitud:", error);
      setErrorMessage("Hubo un problema al registrarse. Inténtalo de nuevo.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="register-container">
      <h2>Registro</h2>
      <form className="register-form" onSubmit={handleRegister}>
        <div className="form-group">
          <label htmlFor="name">Nombre:</label>
          <input
            type="text"
            id="name"
            placeholder="Introduce tu nombre"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="username">Usuario:</label>
          <input
            type="text"
            id="username"
            placeholder="Introduce tu usuario"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="email">Correo Electrónico:</label>
          <input
            type="email"
            id="email"
            placeholder="Introduce tu correo"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="password">Contraseña:</label>
          <input
            type="password"
            id="password"
            placeholder="Introduce tu contraseña"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>

        {errorMessage && <p className="error">{errorMessage}</p>}
        <button type="submit" disabled={loading}>
          {loading ? "Cargando..." : "Registrarse"}
        </button>
        <p className="login-link">
          ¿Ya tienes una cuenta?{" "}
          <button
            className="login-button"
            onClick={() => navigate("/login")}
          >
            Inicia sesión aquí
          </button>
        </p>
      </form>
    </div>
  );
};

export default Register;

// frontend/src/app/components/register/register.component.ts
import { Component, Signal, signal } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  standalone: true,
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  // Declaración de señales
  name = signal('');
  username = signal('');
  email = signal('');
  password = signal('');

  constructor(private router: Router) {}

  // Métodos para actualizar señales
  updateName(value: string) {
    this.name.update(() => value);
  }

  updateUsername(value: string) {
    this.username.update(() => value);
  }

  updateEmail(value: string) {
    this.email.update(() => value);
  }

  updatePassword(value: string) {
    this.password.update(() => value);
  }

  goToLogin() {
    this.router.navigate(['/login']);
  }

  // Método para manejar el registro
  onRegister(event: Event) {
    event.preventDefault();

    const registerData = {
      name: this.name(),
      username: this.username(),
      email: this.email(),
      password: this.password(),
    };

    if (
      registerData.name &&
      registerData.username &&
      registerData.email &&
      registerData.password
    ) {
      console.log('Intentando registrar con:', registerData);

      // Aquí iría la lógica para realizar la petición al API Gateway
      // Ejemplo ficticio:
      // this.authService.register(registerData).subscribe(
      //   (response) => {
      //     alert('Usuario registrado exitosamente');
      //     this.router.navigate(['/login']);
      //   },
      //   (error) => {
      //     console.error('Error durante el registro', error);
      //     alert('Hubo un problema al registrarse. Inténtalo de nuevo.');
      //   }
      // );
    } else {
      alert('Por favor, completa todos los campos.');
    }
  }
}

<div class="register-container">
    <h2>Registro</h2>
    <form (submit)="onRegister($event)">
      <div class="form-group">
        <label for="name">Nombre Completo:</label>
        <input
          type="text"
          id="name"
          placeholder="Introduce tu nombre completo"
          [value]="name()"
          (input)="updateName($any($event.target).value)"
          required
        />
      </div>
  
      <div class="form-group">
        <label for="username">Nombre de Usuario:</label>
        <input
          type="text"
          id="username"
          placeholder="Introduce tu nombre de usuario"
          [value]="username()"
          (input)="updateUsername($any($event.target).value)"
          required
        />
      </div>
  
      <div class="form-group">
        <label for="email">Correo Electrónico:</label>
        <input
          type="email"
          id="email"
          placeholder="Introduce tu correo electrónico"
          [value]="email()"
          (input)="updateEmail($any($event.target).value)"
          required
        />
      </div>
  
      <div class="form-group">
        <label for="password">Contraseña:</label>
        <input
          type="password"
          id="password"
          placeholder="Introduce tu contraseña"
          [value]="password()"
          (input)="updatePassword($any($event.target).value)"
          required
        />
      </div>
  
      <button type="submit" class="btn">Registrarse</button>
      <p class="login-link">
        ¿Ya tienes una cuenta?
        <button (click)="goToLogin()">Inicie sesión aquí</button>
      </p>
    </form>
  </div>
