// frontend/src/app/components/home/home.component.ts
import { Component, Signal, computed, effect, signal } from '@angular/core';
import { Router } from '@angular/router';

interface Food {
  id: string;
  name: string;
  image?: string;
  calories: number;
  protein: number;
}

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  foods = signal<Food[]>([]);
  loading = signal(true);
  errorMessage = signal<string | null>(null);

  constructor(private router: Router) {
    this.loadFoods();
  }

  // Simulación de carga de datos
  loadFoods() {
    this.loading.set(true);
    setTimeout(() => {
      try {
        this.foods.set([
          { id: '1', name: 'Manzana', image: '/assets/apple.png', calories: 52, protein: 0.3 },
          { id: '2', name: 'Plátano', image: '/assets/banana.png', calories: 96, protein: 1.3 },
          { id: '3', name: 'Brócoli', image: '/assets/broccoli.png', calories: 55, protein: 3.7 },
        ]);
        this.errorMessage.set(null);
      } catch (error) {
        this.errorMessage.set('Error al cargar los alimentos');
      } finally {
        this.loading.set(false);
      }
    }, 1000);
  }

  // Redirección al perfil
  goToProfile() {
    this.router.navigate(['/profile']);
  }

  // Redirección al login
  goToLogin() {
    this.router.navigate(['/login']);
  }

  // Detalles de un alimento
  viewDetails(foodId: string) {
    this.router.navigate(['/food', foodId]);
  }
}





<div class="header">
  <img src="/assets/logo.png" alt="Logo" class="logo" />
  <button (click)="goToProfile()">Perfil</button>
  <button (click)="goToLogin()">Iniciar sesión</button>
</div>

<div class="home-container">

  <div class="food-list">
    <ng-container *for="let food of foods()">
      <div class="food-card">
        <h3>{{ food.name }}</h3>
        <img [src]="food.image || '/assets/default-food.png'" alt="{{ food.name }}" />
        <p>Calorías: {{ food.calories }}</p>
        <p>Proteína: {{ food.protein }} g</p>
        <button (click)="viewDetails(food.id)">Ver detalles</button>
      </div>
    </ng-container>
  </div>
</div>

<div class="footer">
  <p>&copy; 2024 NutriFit</p>
</div>

// frontend-react/src/pages/Home.jsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "./Home.css";

const Home = () => {
    const [foods, setFoods] = useState([]);
    const [loading, setLoading] = useState(true);
    const [errorMessage, setErrorMessage] = useState("");
    const navigate = useNavigate();

    useEffect(() => {
        const fetchFoods = async () => {
            try {
                const response = await fetch("http://127.0.0.1:8000/foods");
                if (!response.ok) {
                    throw new Error("Error al obtener los alimentos");
                }
                const data = await response.json();
                setFoods(data);
            } catch (error) {
                setErrorMessage("No se pudieron cargar los alimentos. Intenta más tarde.");
            } finally {
                setLoading(false);
            }
        };
        fetchFoods();
    }, []);

    const handleLogout = () => {
        navigate("/login");
    };

    return (
        <div className="home-container">
            <header className="home-header">
                <div className="logo">NutriFit</div>
                <div className="header-buttons">
                    <button onClick={() => alert("Ir al perfil no funcional")}>Perfil</button>
                    <button onClick={handleLogout}>Cerrar Sesión</button>
                </div>
            </header>

            <div className="home-content">
                <aside className="sidebar">
                    <p>¡Explora!</p>
                    <ul>
                        <li>Verduras</li>
                        <li>Frutas</li>
                        <li>Bebidas</li>
                        <li>Snacks</li>
                    </ul>
                </aside>
                <main className="main-content">
                    {loading && <p>Cargando alimentos...</p>}
                    {errorMessage && <p className="error-message">{errorMessage}</p>}
                    {!loading && !errorMessage && (
                        <div className="food-grid">
                            {foods.map((food) => (
                                <div className="food-card" key={food._id}>
                                    <h3>{food.name}</h3>
                                    <p>Tipo: {food.type}</p>
                                    <p>Calorías: {food.calories}</p>
                                    <p>Proteínas: {food.protein}g</p>
                                    <button className="details-button" onClick={() => navigate(`/foods/${food._id}`)}>
                                        Ver Detalles
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}
                </main>
            </div>

            <footer className="home-footer">
                <p>&copy; 2025 NutriFit. Todos los derechos reservados.</p>
            </footer>
        </div>
    );
};

export default Home;
